server:
#    port: 8081
    port: 80

spring:
    datasource:
        username: root
        password: 1qazzxcvbnm~
#        password: 12345678
        #?serverTimezone=UTC???????
        url: jdbc:mysql://localhost:3306/ds?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource

mybatis:
    type-aliases-package: com.example.dsgeneral.data
    mapper-locations: classpath:mapper/*.xml